version: '3'

services:
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.16.0
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - tracing
  address-ms:
    build:
      context: ./address
    environment:
      JAEGER_SENDER_HOST: jaeger
      JAEGER_SENDER_PORT: 6831
    ports:
      - 8080:8080
    links:
      - jaeger
    networks:
      - tracing
networks:
  tracing:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv4: "true"